// Description: This file contains the soil codes and their respective values.
const soilcodes = [
    {
        value: 1100,
        name: "Sand",
        display: "Sand",
        soilCategory: ["Sand"],
    },
    {
        value: 1200,
        name: "ClayeySand",
        display: "Toniger Sand",
        soilCategory: ["Sand", "Clay"],
    },
    {
        value: 2100,
        name: "LoamySand",
        display: "Sandiger Lehm",
        soilCategory: ["Sand", "Loam"],
    },
    {
        value: 2200,
        name: "HeavilyLoamySand",
        display: "Stark sandiger Lehm",
        soilCategory: ["Sand", "Loam", "Clay"],
    },
    {
        value: 3100,
        name: "Loam",
        display: "Lehm",
        soilCategory: ["Loam"],
    },
    {
        value: 3200,
        name: "SandyLoam",
        display: "Lehmiger Sand",
        soilCategory: ["Loam", "Sand"],
    },
    {
        value: 4100,
        name: "Clay",
        display: "Ton",
        soilCategory: ["Clay"],
    },
    {
        value: 4200,
        name: "HeavyLoam",
        display: "Schwerer Lehm",
        soilCategory: ["Clay", "Loam"],
    },
    {
        value: 5000,
        name: "Peat",
        display: "Torf",
        soilCategory: ["Peat"],
    },
    {
        value: 6110,
        name: "SandPeat",
        display: "Sandiger Torf",
        soilCategory: ["Peat", "Sand"],
    },
    {
        value: 6120,
        name: "LoamySandPeat",
        display: "Sandiger Lehm mit Torf",
        soilCategory: ["Peat", "Loam", "Sand"],
    },
    {
        value: 6130,
        name: "LoamPeat",
        display: "Lehmiger Torf",
        soilCategory: ["Peat", "Loam"],
    },
    {
        value: 6140,
        name: "ClayPeat",
        display: "Toniger Torf",
        soilCategory: ["Peat", "Clay"],
    },
    {
        value: 6210,
        name: "PeatSand",
        display: "Torf mit Sand",
        soilCategory: ["Sand", "Peat"],
    },
    {
        value: 6220,
        name: "PeatLoamySand",
        display: "Torf mit sandigem Lehm",
        soilCategory: ["Sand", "Loam", "Peat"],
    },
    {
        value: 6230,
        name: "PeatLoam",
        display: "Torf mit Lehm",
        soilCategory: ["Loam", "Peat"],
    },
    {
        value: 6240,
        name: "PeatClay",
        display: "Torf mit Ton",
        soilCategory: ["Clay", "Peat"],
    },
    {
        value: 7110,
        name: "SandOnSandyLoam",
        display: "Sand auf sandigem Lehm",
        soilCategory: ["Sand", "Loam"],
    },
    {
        value: 7120,
        name: "SandOnLoam",
        display: "Sand auf Lehm",
        soilCategory: ["Loam", "Sand"],
    },
    {
        value: 7130,
        name: "SandOnHeavyLoam",
        display: "Sand auf schwerem Lehm",
        soilCategory: ["Clay", "Loam", "Sand"],
    },
    {
        value: 7140,
        name: "SandOnClay",
        display: "Sand auf Ton",
        soilCategory: ["Clay", "Sand"],
    },
    {
        value: 7210,
        name: "ClayeySandOnLoam",
        display: "Toniger Sand auf Lehm",
        soilCategory: ["Loam", "Clay", "Sand"],
    },
    {
        value: 7220,
        name: "ClayeySandOnHeavyLoam",
        display: "Toniger Sand auf schwerem Lehm",
        soilCategory: ["Clay", "Loam", "Sand"],
    },
    {
        value: 7230,
        name: "ClayeySandOnClay",
        display: "Toniger Sand auf Ton",
        soilCategory: ["Clay", "Sand"],
    },
    {
        value: 7310,
        name: "LoamySandOnHeavyLoam",
        display: "Sandiger Lehm auf schwerem Lehm",
        soilCategory: ["Clay", "Loam", "Sand"],
    },
    {
        value: 7320,
        name: "LoamySandOnSand",
        display: "Sandiger Lehm auf Sand",
        soilCategory: ["Sand", "Loam"],
    },
    {
        value: 7330,
        name: "LoamySandOnClay",
        display: "Sandiger Lehm auf Ton",
        soilCategory: ["Clay", "Sand", "Loam"],
    },
    {
        value: 7400,
        name: "HeavilyLoamySandOnClay",
        display: "Stark sandiger Lehm auf Ton",
        soilCategory: ["Clay", "Sand", "Loam"],
    },
    {
        value: 7510,
        name: "ClayOnHeavilyLoamySand",
        display: "Ton auf stark sandigem Lehm",
        soilCategory: ["Sand", "Clay", "Loam"],
    },
    {
        value: 7510,
        name: "ClayOnHeavilyLoamySand",
        display: "Ton auf stark sandigem Lehm",
        soilCategory: ["Sand", "Clay", "Loam"],
    },
    {
        value: 7520,
        name: "ClayOnLoamySand",
        display: "Ton auf sandigem Lehm",
        soilCategory: ["Sand", "Loam", "Clay"],
    },
    {
        value: 7530,
        name: "ClayOnClayeySand",
        display: "Ton auf tonigem Sand",
        soilCategory: ["Sand", "Clay"],
    },
    {
        value: 7540,
        name: "ClayOnSand",
        display: "Ton auf Sand",
        soilCategory: ["Sand", "Clay"],
    },
    {
        value: 7610,
        name: "HeavyLoamOnLoamySand",
        display: "Schwerer Lehm auf sandigem Lehm",
        soilCategory: ["Sand", "Loam", "Clay"],
    },
    {
        value: 7620,
        name: "HeavyLoamOnClayeySand",
        display: "Schwerer Lehm auf tonigem Sand",
        soilCategory: ["Sand", "Clay", "Loam"],
    },
    {
        value: 7630,
        name: "HeavyLoamOnSand",
        display: "Schwerer Lehm auf Sand",
        soilCategory: ["Sand", "Clay", "Loam"],
    },
    {
        value: 7710,
        name: "LoamOnClayeySand",
        display: "Lehm auf tonigem Sand",
        soilCategory: ["Sand", "Clay", "Loam"],
    },
    {
        value: 7720,
        name: "LoamOnSand",
        display: "Lehm auf Sand",
        soilCategory: ["Sand", "Loam"],
    },
    {
        value: 7800,
        name: "SandyLoamOnSand",
        display: "Sandiger Lehm auf Sand",
        soilCategory: ["Sand", "Loam"],
    },
    {
        value: 8110,
        name: "SandOnPeat",
        display: "Sand auf Torf",
        soilCategory: ["Peat", "Sand"],
    },
    {
        value: 8120,
        name: "LoamySandOnPeat",
        display: "Sandiger Lehm auf Torf",
        soilCategory: ["Peat", "Sand", "Loam"],
    },
    {
        value: 8130,
        name: "LoamOnPeat",
        display: "Lehm auf Torf",
        soilCategory: ["Peat", "Loam"],
    },
    {
        value: 8210,
        name: "PeatOnSand",
        display: "Torf auf Sand",
        soilCategory: ["Sand", "Peat"],
    },
    {
        value: 8220,
        name: "PeatOnLoamySand",
        display: "Torf auf sandigem Lehm",
        soilCategory: ["Sand", "Loam", "Peat"],
    },
    {
        value: 8230,
        name: "PeatOnLoam",
        display: "Torf auf Lehm",
        soilCategory: ["Loam", "Peat"],
    },
    {
        value: 8240,
        name: "PeatOnClay",
        display: "Torf auf Ton",
        soilCategory: ["Clay", "Peat"],
    },
    {
        value: 9120,
        name: "LoamToPeatTransition",
        display: "Übergang von Lehm zu Torf",
        soilCategory: ["Loam", "Peat"],
    },
    {
        value: 9130,
        name: "LoamySandWithHighStoneContent",
        display: "Sandiger Lehm mit hohem Steinanteil",
        soilCategory: ["Sand", "Loam"],
    },
    {
        value: 9140,
        name: "LoamWithHighStoneContent",
        display: "Lehm mit hohem Steinanteil",
        soilCategory: ["Loam"],
    },
];

export default soilcodes;

